version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: truelayer-pokemon-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # ExternalApis__FunTranslations__ApiKey: ${FUNTRANS_API_KEY}  # sblocca piani a pagamento
